### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by mfactory88** [mfactory88/gryff-restaurant-search#1]
- wireframe
- create touch files - html, js, css
- css framework - foundation
- jquery
- collaborators clone repo
- collaborators would have feature branch to work on

**Comment by mfactory88** [comment]
wireframe - https://docs.google.com/presentation/d/1Qmu2xZOfR97cS5gixqCjjrtwsgR5jlz3dMKRVDkqAdU/edit#slide=id.g1330cc142f0_0_0

**Comment by SLachelier** [comment]
https://get.foundation/
